docker:
- changed-files:
  - any-glob-to-any-file: ['Dockerfile', 'docker-compose.yaml']
application:
- changed-files:
  - any-glob-to-any-file: ['src/**/*', 'package.json', 'package-lock.json', '.env*']
  - all-globs-to-all-files: '!src/docs/*'
config:
- changed-files:
  - any-glob-to-any-file: ['tsconfig.json', '.eslintrc.js', '.gitignore', '.npmrc', '.prettierignore']
ci:
- changed-files:
  - any-glob-to-any-file: ['.github/**/*']
docs:
- changed-files:
  - any-glob-to-any-file: ['README.md']
feature:
- head-branch: ['^feature', 'feature']
